services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-wgcna}
    networks:
      - app-network

  redis:
    image: redis:6.0-alpine
    networks:
      - app-network

  db_setup:
    image: coexplore:dev
    container_name: db_setup
    env_file:
      - .env
    volumes:
      - ./app:/app
      - ./output:/output
      - ./scripts/generate_db.py:/generate_db.py
      - ./scripts/wait_for_postgres.py:/wait_for_postgres.py
      - ./package:/CoExPlore/package
    working_dir: /
    command: >
      bash -c "python wait_for_postgres.py && python generate_db.py && touch /output/db_done.txt"
    depends_on:
      - postgres
      - redis
    networks:
      - app-network

  web:
    image: coexplore:dev
    container_name: flask_app
    env_file:
      - .env
    volumes:
      - ./app:/app
      - ./output:/output
      - ./package:/CoExPlore/package
    working_dir: /app
    command: >
      bash -c "
        while [ ! -f /output/db_done.txt ]; do
          echo 'Waiting for DB setup to finish...'
          sleep 30
        done;
        flask run --host=0.0.0.0 --port=5001
      "
    ports:
      - "5001:5001"
    depends_on:
      - db_setup
      - redis
    networks:
      - app-network

  worker:
    image: coexplore:dev
    container_name: celery_worker
    env_file:
      - .env
    volumes:
      - ./app:/app
      - ./output:/output
      - ./package:/CoExPlore/package
    working_dir: /app
    command: >
      bash -c "
        while [ ! -f /output/db_done.txt ]; do
          echo 'Waiting for DB setup to finish...'
          sleep 30
        done;
        celery -A app.celery worker --loglevel=debug
      "
    depends_on:
      - db_setup
      - redis
    networks:
      - app-network

networks:
  app-network:
