# Mount package and app directories as volumes for development

# Use Miniconda as the base image
FROM continuumio/miniconda3:latest

# Set the working directory
WORKDIR /CoExPlore

# Copy environment files (requirements and conda environment)
COPY app/requirements.txt app/environment.yml ./

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends graphviz \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Create conda environment from environment.yml
RUN conda env create -f environment.yml && conda clean -afy

# Set environment path
ENV PATH=/opt/conda/envs/WGCNA_APP/bin:$PATH

# Install Python dependencies (ohne dein Package)
RUN pip install --no-cache-dir -r requirements.txt

# Install custom packages: PyWGCNA, Snakemake and specific Pulp version
RUN pip install git+https://github.com/Mfkessler/PyWGCNA.git \
    && pip install snakemake pulp==2.7.0

# Set PYTHONPATH so that Python auch im Container in /CoExPlore/package nach Modulen sucht
ENV PYTHONPATH=/CoExPlore/package

# Default command
CMD ["bash"]
