services:
  wgcna_pipeline:
    image: coexplore-pipeline:latest
    container_name: wgcna_pipeline
    env_file:
      - .env
    volumes:
      - ./input:/CoExPlore/input:z
      - ./output:/CoExPlore/output:z
      - ./pipeline/config.yml:/CoExPlore/config.yml:z
      - ./pipeline/Snakefile:/CoExPlore/Snakefile:z
      - ./app:/app:z
    working_dir: /CoExPlore
    command: >
      bash -c "snakemake --cores 4 && touch /CoExPlore/output/pipeline_done.txt"
