services:
  wgcna_pipeline:
    image: wgcna_image:pipeline
    container_name: wgcna_pipeline
    env_file:
      - .env
    volumes:
      - ./input:/wgcna-pipeline/input
      - ./output:/wgcna-pipeline/output
      - ./wgcna-pipeline/config.yml:/wgcna-pipeline/config.yml
      - ./wgcna-pipeline/Snakefile:/wgcna-pipeline/Snakefile
      - ./wgcna-app:/wgcna-app
    working_dir: /wgcna-pipeline
    command: >
      bash -c "snakemake --cores 4 && touch /wgcna-pipeline/output/pipeline_done.txt"
