# Dockerfile.dev for CoExPlore development
# Mount app, editable package

FROM coexplore-base:latest

# Set the working directory
WORKDIR /wgcna-app

# Copy the package temporarily for installation
COPY package /tmp/wgcna-package/

# Install the persistent package (without dependencies)
RUN pip install --no-deps /tmp/wgcna-package

# Clean up temporary files and pip cache
RUN rm -rf /tmp/wgcna-package ~/.cache/pip /tmp/* /var/tmp/* && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Set PYTHONPATH so that Python searches for modules in /CoExPlore/package within the container
ENV PYTHONPATH=/CoExPlore/package

# Default command
CMD ["bash"]