# Configuration file for CoExPlore pipeline
# This file contains the parameters to run the pipeline
# The parameters are divided into two categories: mandatory and optional
# The mandatory parameters are required to run the pipeline

# Mandatory parameters:
species:
  - "Physcomitrella patens"
  
name:
  - "PP"

count_matrix:
  - "/CoExPlore/input/ppatens/PPatens.PSEUDO_BULK.EXPR.matrix"

sample_mapping:
  - "/CoExPlore/input/ppatens/sample_mapping.tsv"

# Optional metadata files:
iprid:
  - "/CoExPlore/input/ppatens/gene2interpro.tsv"

goid:
  - "/CoExPlore/input/ppatens/gene2go.tsv"

orthogroups: ""

# Output parameters
save_tom: true # Required for using the Co-Expression Network Analysis 
save_adjacency_matrix: false
save_WGCNA: false
figure_type: "png"
reduce_matrix: false

# WGCNA parameters
wgcna_parameters:
  TPMcutoff: 1
  powers: null              # If null, the pipeline will calculate the best power
  RsquaredCut: 0.9
  MeanCut: 50
  networkType: "signed hybrid"
  TOMType: "signed"
  minModuleSize: 30
  naColor: "grey"
  cut: inf
  MEDissThres: 0.2


output_path: "/CoExPlore/output"

app_path: "/app"
