species: "Species 1"
name: "S1"

count_matrix: "/CoExPlore/input/testdata_out/S1.isoform.TMM.matrix"
sample_mapping: "/CoExPlore/input/testdata_out/S1.sample_mapping.tsv"
iprid: "/CoExPlore/input/testdata_out/S1.iprid.tsv"
goid: "/CoExPlore/input/testdata_out/S1.goid.tsv"
orthogroups: "/CoExPlore/input/testdata_out/N0.tsv"

save_tom: true
save_adjacency_matrix: false
save_WGCNA: false
figure_type: "png"
reduce_matrix: false

output_path: "/CoExPlore/output/"

app_path: "/app"