species:
  - "Species 1"
  - "Species 2"
  
name:
  - "S1"
  - "S2"

count_matrix:
  - "/CoExPlore/input/testdata_out/S1.isoform.TMM.matrix"
  - "/CoExPlore/input/testdata_out/S2.isoform.TMM.matrix"

sample_mapping:
  - "/CoExPlore/input/testdata_out/S1.sample_mapping.tsv"
  - "/CoExPlore/input/testdata_out/S2.sample_mapping.tsv"

iprid:
  - "/CoExPlore/input/testdata_out/S1.iprid.tsv"
  - "/CoExPlore/input/testdata_out/S2.iprid.tsv"

goid:
  - "/CoExPlore/input/testdata_out/S1.goid.tsv"
  - "/CoExPlore/input/testdata_out/S2.goid.tsv"

orthogroups: "/CoExPlore/input/testdata_out/N0.tsv"

save_tom: true
save_adjacency_matrix: false
save_WGCNA: false
figure_type: "png"
reduce_matrix: false

output_path: "/CoExPlore/output"

app_path: "/app"