species: "Test data"
name: "TD"

count_matrix: "/wgcna-pipeline/input/test_data/td.isoform.TMM.filtered.matrix"
sample_mapping: "/wgcna-pipeline/input/test_data/td.sample_mapping.filtered.tsv"
iprid: "/wgcna-pipeline/input/test_data/td.iprid.filtered.tsv"
goid: "/wgcna-pipeline/input/test_data/td.goid.filtered.tsv"
orthogroups: ""

save_tom: true
save_adjacency_matrix: false
save_WGCNA: false
figure_type: "png"
reduce_matrix: false

output_path: "/wgcna-pipeline/output/"

app_path: "/wgcna-app"