services:
  web:
    image: wgcna_image:dev
    container_name: flask_app_dev
    command: sh -c "pip install -e /wgcna-package && flask run --host=0.0.0.0 --port=5002"
    env_file:
      - /vol/blast/wgcna/wgcna-app/envs/.env
    volumes:
      - /vol/blast/wgcna/wgcna-app:/wgcna-app
      - /vol/blast/wgcna/wgcna-package:/wgcna-package
      - /vol/share/ranomics_app/data/h5ad:/vol/share/ranomics_app/data/h5ad
      - /vol/share/ranomics_app/data:/vol/share/ranomics_app/data
      - /vol/blast/wgcna/wgcna-app/output/dev:/wgcna-app/output/dev
    ports:
      - "5002:5002"
    depends_on:
      - redis
      - worker
    networks:
      - app-network

  worker:
    image: wgcna_image:dev
    container_name: celery_worker_dev
    command: sh -c "pip install -e /wgcna-package && celery -A app.celery worker --loglevel=debug"
    env_file:
      - /vol/blast/wgcna/wgcna-app/envs/.env
    volumes:
      - /vol/blast/wgcna/wgcna-app:/wgcna-app
      - /vol/blast/wgcna/wgcna-package:/wgcna-package
      - /vol/share/ranomics_app/data/h5ad:/vol/share/ranomics_app/data/h5ad
      - /vol/share/ranomics_app/data:/vol/share/ranomics_app/data
      - /vol/blast/wgcna/wgcna-app/output/dev:/wgcna-app/output/dev
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:6.0-alpine
    container_name: redis_dev
    networks:
      - app-network

networks:
  app-network:
    name: dev_app_network
    driver: bridge
