from setuptools import setup, find_packages

setup(
	name='wgcna-package',
	version='0.1.0',
	packages=find_packages(),
	description='WGCNA package for Python',
	author='Micha Frederick Keßler',
	author_email='Micha.Kessler@computational.bio.uni-giessen.de',
	license='MIT',
	install_requires=[
		'anndata',
		'bokeh',
		'celery',
		'Flask',
		'Flask_Cors',
		'goatools',
		'gunicorn',
		'h5py',
		'ipython',
		'Jinja2',
		'kaleido',
		'matplotlib',
		'matplotlib_venn',
		'memory_profiler',
		'networkx',
		'numpy',
		'pandas',
		'Pillow',
		'plotly',
		'psycopg2-binary',
		'pytest',
		'python_igraph',
		'PyYAML',
		'redis',
		'scanpy',
		'scikit_learn',
		'scipy',
		'seaborn',
		'setuptools',
		'SQLAlchemy',
		'statsmodels',
		'UpSetPlot',
	],
	classifiers=[
		'Programming Language :: Python :: 3',
		'License :: OSI Approved :: MIT License',
	],
)
