name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Setup and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Move metadata file
        run: cp metadata_dict.json /metadata_dict.json

      - name: Set up Python 3.13.2
        uses: actions/setup-python@v4
        with:
          python-version: "3.13.2"

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          pip install ./package
          pip install git+https://github.com/Mfkessler/PyWGCNA.git

      - name: Run Tests
        run: |
          pytest ./package/tests/ --disable-warnings --maxfail=5
