name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Setup and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Conda and Create Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.8.19"
          environment-file: package/environment.yml
          activate-environment: wgcna-package

      - name: Install Dependencies
        run: |
          pip install pytest
          pip install ./package
          pip install git+https://github.com/Mfkessler/PyWGCNA.git

      - name: Run Tests
        run: |
          pytest ./package/tests/ --disable-warnings --maxfail=5
