name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.8.19"
          environment-file: package/environment.yml
          activate-environment: wgcna-package

      - name: Install Dependencies
        run: |
          pip install pytest
          pip install ./package
          pip install git+https://github.com/Mfkessler/PyWGCNA.git

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Activate Environment and Run Tests
        run: |
          conda activate wgcna-package
          pytest ./package/tests/ --disable-warnings --maxfail=5
